development:
  adapter: postgresql
  encoding: unicode
  database: radiofriendly_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: radiofriendly_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: radiofriendly_production
  pool: 5
  username:
  password:
